server:
  port: 8086
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: ERROR
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: 101119
    driver-class-name: org.postgresql.Driver